### ISSUE TITLE
some minor fix suggestions

### ISSUE THREAD

**Issue by Yang2888** [fjiangAI/MMAPIS#3]
Thank you for your work, I think it may be the current sota for academic paper pdf extraction and summary. However I have some suggestions:

1. replace the https://xxxx  in configs to current openai api website (it is just after the xxxx in the configs notation)

2. use request library instead of openai library as default api call method (the openai library api goes wrong easily while request is more stable)

3. add a script to automatically start the 3 servers. I made one for windows: 

```
#!/bin/bash

# Start Backend in a new PowerShell window
powershell.exe -Command "Start-Process powershell -ArgumentList 'cd backend; conda init powershell; conda activate MMAPIS_backend; uvicorn backend:app --reload'"

# Start Middleware in a new PowerShell window
powershell.exe -Command "Start-Process powershell -ArgumentList 'cd middleware; conda init powershell; conda activate MMAPIS_middleware; uvicorn middleware:app --reload --port 8005'"

# Start Client in a new PowerShell window
powershell.exe -Command "Start-Process powershell -ArgumentList 'cd client; conda init powershell; conda activate MMAPIS_client; streamlit run app.py'"
``` 

4. delete the "nvidia-nccl-cu12==2.20.5" in backend/config/requirements.txt, which cannot be installed and do not function inside the project

5. change the cuda using cpu warning to error / red-colored font, which may help save some debug time

**Comment by fjiangAI** [comment]
> Thank you for your work, I think it may be the current sota for academic paper pdf extraction and summary. However I have some suggestions:
> 
> 1. replace the https://xxxx  in configs to current openai api website (it is just after the xxxx in the configs notation)
> 2. use request library instead of openai library as default api call method (the openai library api goes wrong easily while request is more stable)
> 3. add a script to automatically start the 3 servers. I made one for windows:
> 
> ```
> #!/bin/bash
> 
> # Start Backend in a new PowerShell window
> powershell.exe -Command "Start-Process powershell -ArgumentList 'cd backend; conda init powershell; conda activate MMAPIS_backend; uvicorn backend:app --reload'"
> 
> # Start Middleware in a new PowerShell window
> powershell.exe -Command "Start-Process powershell -ArgumentList 'cd middleware; conda init powershell; conda activate MMAPIS_middleware; uvicorn middleware:app --reload --port 8005'"
> 
> # Start Client in a new PowerShell window
> powershell.exe -Command "Start-Process powershell -ArgumentList 'cd client; conda init powershell; conda activate MMAPIS_client; streamlit run app.py'"
> ```
> 
> 4. delete the "nvidia-nccl-cu12==2.20.5" in backend/config/requirements.txt, which cannot be installed and do not function inside the project
> 5. change the cuda using cpu warning to error / red-colored font, which may help save some debug time

Thank you very much for your valuable suggestions. We will update it accordingly.
